### ISSUE TITLE
Unable to fetch posts

### ISSUE THREAD

**Issue by CCHaynes112** [JackhammerYT/RedDownloader#22]
When I run this:
```
from RedDownloader import RedDownloader
RedDownloader.DownloadVideosBySubreddit("videos", 10)
```

I get the following error:
```
Fetching Posts...
Unable to fetch posts
Expecting value: line 1 column 1 (char 0)
```

And when I navigate to `https://jackhammer.pythonanywhere.com/`, it tries the load the page forever, and very rarely will it actually get to the page, though sometimes it does. So I assume this is an issue with the server? Not quite sure.

**Comment by PaulManart** [comment]
Considering the Status: Online (200) I assume that there is a cap on how many users can simultaneously use this script?

**Comment by JackhammerYT** [comment]
@PaulManart and @CCHaynes112 There was an issue with over server loading, which has been fixed make sure to download RedDownloader 3.3.0. The website should also open swiftly now.

**Comment by HardikRa** [comment]
Still facing this issue, consider open-sourcing the code of your server so people can set it up personally? @JackhammerYT
